version: "3"

services:
  api:
    container_name: grocia-api
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${DOCKER_PORT:-8686}:${DOCKER_PORT:-8686}"
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
    command:
      - uvicorn
      - src.main:app
      - --host
      - ${DOCKER_HOST}
      - --port
      - ${DOCKER_PORT}
      - --reload
  db:
    container_name: grocia-postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
