version: "3"

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini
      - ./scripts:/code/scripts
    command: uvicorn src.main:app --host ${DOCKER_HOST} --port ${DOCKER_PORT} --reload
    depends_on:
      - app_db

  app_db:
    container_name: app_db
    hostname: app_db
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    external: true
    name: app_network
