version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${DOCKER_PORT:-8686}:${DOCKER_PORT:-8686}"
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "${DOCKER_HOST:-0.0.0.0}",
        "--port",
        "${DOCKER_PORT:-8686}",
        "--reload",
      ]
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
