version: "3"

services:
  api:
    container_name: grocia-api
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${DOCKER_PORT:-8686}:${DOCKER_PORT:-8686}"
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
